DerethForever.Web/Models/CachePwn/GeneratorTable.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using Newtonsoft.Json;

namespace DerethForever.Web.Models.CachePwn
{
    public class GeneratorTable
    {
        [JsonProperty("delay")]
        public float Delay { get; set; }

        [JsonProperty("frame")]
        public Frame Frame { get; set; } = new Frame();

        [JsonProperty("initCreate")]
        public uint InitCreate { get; set; }

        [JsonProperty("maxNum")]
        public uint MaxNumber { get; set; }

        [JsonProperty("objcell_id")]
        public uint ObjectCell { get; set; }

        [JsonProperty("probability")]
        public double Probability { get; set; }

        [JsonProperty("ptid")]
        public uint PaletteId { get; set; }

        [JsonProperty("shade")]
        public float Shade { get; set; }

        [JsonProperty("slot")]
        public uint Slot { get; set; }

        [JsonProperty("stackSize")]
        public int StackSize { get; set; }

        [JsonProperty("type")]
        public uint WeenieClassId { get; set; }

        [JsonProperty("whenCreate")]
        public uint WhenCreate { get; set; }

        [JsonProperty("whereCreate")]
        public uint WhereCreate { get; set; }
    }
}

DerethForever.Web/Models/CachePwn/Vital.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace DerethForever.Web.Models.CachePwn
{
    public class Vital
    {
        [JsonProperty("cp_spent")]
        public uint? XpSpent { get; set; }

        [JsonProperty("level_from_cp")]
        public uint? LevelFromCp { get; set; }

        [JsonProperty("init_level")]
        public uint? Ranks { get; set; }

        [JsonProperty("current")]
        public uint? Current { get; set; }

        public Shared.Ability Convert(Enums.AbilityId ability)
        {
            var a = new Shared.Ability();
            
            a.AbilityId = (int)ability;
            a.Ranks = Ranks;
            a.ExperienceSpent = XpSpent;
            a.Base = (Current - Ranks);

            return a;
        }
        
        public static Vital Convert(Shared.Ability ability)
        {
            Vital v = new Vital();
            v.Ranks = ability.Ranks;
            v.Current = ability.Base + ability.Ranks;
            v.XpSpent = ability.ExperienceSpent;
            v.LevelFromCp = 0;
            return v;
        }
    }
}

DerethForever.Web/Models/Enums/UiEffects.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.ComponentModel.DataAnnotations;

namespace DerethForever.Web.Models.Enums
{
    [Flags]
    public enum UiEffects
    {
        [Display(Name       = "Undef")]
        Undef               = 0x0000,
        [Display(Name       = "Magical")]
        Magical             = 0x0001,
        [Display(Name       = "Poisoned")]
        Poisoned            = 0x0002,
        [Display(Name       = "Boost Health")]
        BoostHealth         = 0x0004,
        [Display(Name       = "Boost Mana")]
        BoostMana           = 0x0008,
        [Display(Name       = "Boost Stamina")]
        BoostStamina        = 0x0010,
        [Display(Name       = "Fire")]
        Fire                = 0x0020,
        [Display(Name       = "Lightning")]
        Lightning           = 0x0040,
        [Display(Name       = "Frost")]
        Frost               = 0x0080,
        [Display(Name       = "Acid")]
        Acid                = 0x0100,
        [Display(Name       = "Bludgeoning")]
        Bludgeoning         = 0x0200,
        [Display(Name       = "Slashing")]
        Slashing            = 0x0400,
        [Display(Name       = "Piercing")]
        Piercing            = 0x0800,
        [Display(Name       = "Nether")]
        Nether              = 0x1000
    }
}

DerethForever.Web/Models/PreComp/Generator.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DerethForever.Web.Models.PreComp
{
    public class Generator
    {
        public double Probability { get; set; }

        public long Type { get; set; }

        public long Delay { get; set; }

        public long InitCreate { get; set; }

        public long MaxNum { get; set; }

        public long WhenCreate { get; set; }

        public long WhereCreate { get; set; }

        public int StackSize { get; set; }

        public long Shade { get; set; }

        public long PalleteTypeId { get; set; }

        public Position Position { get; set; }

        public long Slot { get; set; }
    }
}

DerethForever.Web/Models/Shared/Ability.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DerethForever.Web.Models.Enums;
using Newtonsoft.Json;

namespace DerethForever.Web.Models.Shared
{
    public class Ability
    {
        [JsonProperty("ability")]
        public int AbilityId { get; set; }

        [JsonIgnore]
        public string AbilityIdBinder
        {
            get { return ((AbilityId)AbilityId).GetName(); }
        }

        public AbilityId TypedAbilityId
        {
            get { return (AbilityId)AbilityId; }
        }

        [JsonProperty("baseValue")]
        public uint? Base { get; set; }

        [JsonProperty("ranks")]
        public uint? Ranks { get; set; }

        [JsonProperty("experienceSpent")]
        public uint? ExperienceSpent { get; set; }

        [JsonProperty("startingValue")]
        public uint? UnbuffedValue { get; set; }
    }
}

DerethForever.Web/Models/Shared/AbilitySet.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DerethForever.Web.Models.Enums;
using Newtonsoft.Json;

namespace DerethForever.Web.Models.Shared
{
    public class AbilitySet
    {
        [JsonProperty("strength")]
        public Ability Strength { get; set; } = new Ability() { AbilityId = (int)AbilityId.Strength, Base = 10 };

        [JsonProperty("endurance")]
        public Ability Endurance { get; set; } = new Ability() { AbilityId = (int)AbilityId.Endurance, Base = 10 };

        [JsonProperty("coordination")]
        public Ability Coordination { get; set; } = new Ability() { AbilityId = (int)AbilityId.Coordination, Base = 10 };

        [JsonProperty("quickness")]
        public Ability Quickness { get; set; } = new Ability() { AbilityId = (int)AbilityId.Quickness, Base = 10 };

        [JsonProperty("focus")]
        public Ability Focus { get; set; } = new Ability() { AbilityId = (int)AbilityId.Focus, Base = 10 };

        [JsonProperty("self")]
        public Ability Self { get; set; } = new Ability() { AbilityId = (int)AbilityId.Self, Base = 10 };
    }
}

DerethForever.Web/Models/Shared/Angles.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using Newtonsoft.Json;

namespace DerethForever.Web.Models.Shared
{
    public class Angles
    {
        [JsonProperty("w")]
        public float W { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }

        [JsonProperty("z")]
        public float Z { get; set; }
    }
}

DerethForever.Web/Controllers/ModelViewerController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DerethForever.Web.Controllers
{
    public class ModelViewerController : BaseController
    {
        [HttpGet]
        public ActionResult Index(int modelId)
        {
            return View();
        }
    }
}

DerethForever.Web/Views/Shared/EditorTemplates/AbilityList.cshtml
@model DerethForever.Web.Models.Shared.AbilitySet

<h3>Attributes</h3>

<div id="abilitiesContainer">
    <div class="row row-spacer">
        <div class="col-md-2"><strong>Ability</strong></div>
        <div class="col-md-1"><strong>Base</strong></div>
        <div class="col-md-2"><strong>Ranks</strong></div>
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Strength, "Ability")
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Endurance, "Ability")
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Coordination, "Ability")
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Quickness, "Ability")
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Focus, "Ability")
    </div>
    <div class="row row-spacer">
        @Html.EditorFor(m => m.Self, "Ability")
    </div>
</div>

DerethForever.Web/Views/Shared/EditorTemplates/BookPages.cshtml
@model List<DerethForever.Web.Models.Shared.BookPage>

<h3>Book Pages</h3>
<input type="hidden" id="PageCount" value="@Model.Count()" />

<div class="row row-spacer">
    <div class="col-md-2"><strong>Page #</strong></div>
    <div class="col-md-2"><strong>Author Name</strong></div>
    <div class="col-md-2"><strong>Author Account</strong></div>
    <div class="col-md-2"><strong>Author Id</strong></div>
    <div class="col-md-2"><strong>Ignore Author</strong></div>
</div>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="col-md-2">
            @Html.HiddenFor(m => m[i].Deleted)
            @Html.TextBoxFor(m => m[i].Page, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.TextBoxFor(m => m[i].AuthorName, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.TextBoxFor(m => m[i].AuthorAccount, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.TextBoxFor(m => m[i].AuthorId, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.CheckBoxFor(m => m[i].IgnoreAuthor)
        </div>
        <div class="col-md-2">
            <input type="button" class="btn btn-xs btn-danger" name="removePage" id="removePage" value="Remove" />
        </div>
    </div>
    <div class="row row-spacer">
        <div class="col-md-10">
            @Html.TextAreaFor(m => m[i].PageText, new { cols = 110, rows = 3, @class = "form-control" })
        </div>
        <div class="col-md-2">
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/BoolPropertyList.cshtml
@using DerethForever.Web.Models.Enums
@model List<DerethForever.Web.Models.Shared.BoolProperty>

<input type="hidden" id="BoolPropertyCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="col-md-3">
            @Html.DisplayFor(m => m[i].PropertyIdBinder)
            @Html.HiddenFor(m => m[i].BoolPropertyId)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="col-md-2">
            @Html.CheckBoxFor(m => m[i].Value, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeProperty" value="Remove" />
        </div>
        <div class="col-md-6">
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@Html.CheckBox("", Model.GetValueOrDefault())

DerethForever.Web/Views/Shared/EditorTemplates/CreateList.cshtml
@using DerethForever.Web.Models.Enums
@using DerethForever.Web.Models.Shared
@model List<DerethForever.Web.Models.Shared.CreationProfile>

<h3>Create List</h3>

<div class="row row-spacer">
    <div class="col-md-2">@(Html.Label("Weenie"))</div>
    <div class="col-md-2">@(Html.Label("Destination"))</div>
    <div class="col-md-1">@(Html.Label("Palette"))</div>
    <div class="col-md-3">@(Html.Label("Shade"))</div>
    <div class="col-md-1">@(Html.Label("Quantity"))</div>
    <div class="col-md-1">@(Html.Label("Bonded"))</div>
    <div class="col-md-4"></div>
</div>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="col-md-2">
            @Html.HiddenFor(m => m[i].CreationProfileGuid)
            @Html.HiddenFor(m => m[i].OwnerId)
            @Html.HiddenFor(m => m[i].Deleted)
            @Html.TextBoxFor(m => m[i].WeenieClassId, new { @class = "form-control weenieClassEntry" })
        </div>
        <div class="col-md-2">
            @Html.EnumDropDownListFor(m => m[i].Destination_Binder, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.TextBoxFor(m => m[i].Palette, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.TextBoxFor(m => m[i].Shade, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.TextBoxFor(m => m[i].StackSize, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.EditorFor(m => m[i].TryToBond)
        </div>
        <div class="col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeCreateItem" value="Remove" />
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/DataIdPropertyList.cshtml
@using DerethForever.Web.Models.Enums
@model List<DerethForever.Web.Models.Shared.DataIdProperty>

<input type="hidden" id="DidPropertyCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="vcenter col-md-3">
            @Html.DisplayFor(m => m[i].PropertyIdBinder)
            @Html.HiddenFor(m => m[i].DataIdPropertyId)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="vcenter col-md-3">
            @Html.TextBoxFor(m => m[i].Value, new { @class = "form-control" })
        </div>
        <div class="vcenter col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeProperty" value="Remove" />
        </div>
        <div class="vcenter col-md-4">
            @if (Model[i].DataIdPropertyId == 1)
            {
                // this is the Setup property, and we can give a link to the model viewer here
                @Html.ActionLink("Model Viewer", "Index", "ModelViewer");
            }
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/FlagsEnum.cshtml
@using DerethForever.Web.Models.Enums
@model Enum

@{var name = ViewData.TemplateInfo.HtmlFieldPrefix; int i = 1;}
@Html.Hidden("", Convert.ToInt32(Model))

@foreach (var r in Enum.GetValues(Model.GetType()))
{
    if (((int)r) < 1)
    {
        continue;
    }

    @Html.CheckBox(((int)r).ToString(), (Convert.ToInt32(Model) & (int)r) > 0,
            new
            {
                onchange = "if ($('#" + name + "_" + ((int)r).ToString() + "').prop('checked')) " +
                    "{ $('#" + name + "').val($('#" + name + "').val() | 0x" + ((int)r).ToString("X") + "); } " +
                    "else " +
                    "{ $('#" + name + "').val($('#" + name + "').val() & ~0x" + ((int)r).ToString("X") + "); }"
            })
    @Html.Raw((r as Enum).GetName() + "&nbsp;&nbsp;&nbsp;")

    if (i % 3 == 0)
    {
        <br/>
    }
    i++;
}

DerethForever.Web/Views/Shared/EditorTemplates/Int64PropertyList.cshtml
@using DerethForever.Web.Models.Enums
@model List<DerethForever.Web.Models.Shared.Int64Property>

<input type="hidden" id="Int64PropertyCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="vcenter col-md-3">
            @Html.DisplayFor(m => m[i].PropertyIdBinder)
            @Html.HiddenFor(m => m[i].Int64PropertyId)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="vcenter col-md-3">
            @Html.TextBoxFor(m => m[i].Value, new { @class = "form-control" })
        </div>
        <div class="vcenter col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeProperty" value="Remove" />
        </div>
        <div class="col-md-5">
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/SpellList.cshtml
@using DerethForever.Web.Models.Enums
@using DerethForever.Web.Models.Shared
@model List<DerethForever.Web.Models.Shared.Spell>

<h3>Spells</h3>

<input type="hidden" id="SpellCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="col-md-4">
            @Html.Label("Probability for " + Spell.GetSpellDescription(Model[i].SpellId))
            @Html.HiddenFor(m => m[i].SpellId)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="col-md-3">
            @Html.TextBoxFor(m => m[i].Probability, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeSpell" value="Remove" />
        </div>
        <div class="col-md-4">
        </div>
    </div>
}